In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,index=range(1, 51),columns=['國文', '英文', '數學', '地理', '歷史'])
scores_df.index.name = "學號"
scores_df.columns.name = "科目"
scores_df

科目  國文  英文   數學   地理   歷史
學號
1   55  61   78   83   60
2   67  87   95   87   60
3   96  60   71   89   56
4   69  54   86   76   84
5   78  74  100   85   90
6   67  90   96   64  100
7   97  65   55   82   91
8   92  93   85   92   61
9   82  62   95   58   83
10  54  96   93   90   56
11  60  71   94   85   97
12  85  92   57   75   65
13  61  89   65   77   50
14  57  59   72   80   99
15  83  75   53   95   96
16  84  75   93   86   99
17  50  85   79   94   58
18  82  72   61   64   90
19  81  89   53   56   57
20  76  84   99   57   59
21  52  65   92   59   86
22  92  63   60   94   94
23  92  78   94   73   96
24  67  87   87   80   97
25  66  52   79   50   98
26  63  76   99   50   76
27  77  72   76   95   86
28  77  96   52   90   97
29  88  66   91   90   91
30  85  71  100   99   59
31  89  82   77   78   51
32  65  73   58   67   83
33  54  76   60   93   61
34  99  53   92   88   97
35  93  55   69   76   63
36  75  95   54   82   69
37  62  61   61   69   59
38  74  71   95   95   80
39  64  67   64   84   66
40  70  97   51   50   62
41  98  84   76   87   82
42  84  73   81   66   66
43  70  79   61   61   89
44  51  84   53   83   92
45  97  50   87   74   85
46  58  86   55   74   89
47  93  76   58   94   60
48  92  65   85   57   65
49  82  54   80   95   61
50  83  86   98  100   89

In [2]:
scores_df1 = scores_df.copy()

In [5]:
def cal1(s):
    return s.sum()
scores_df.apply(cal1,axis=1)

學號
1     337
2     396
3     372
4     369
5     427
6     417
7     390
8     423
9     380
10    389
11    407
12    374
13    342
14    367
15    402
16    437
17    366
18    369
19    336
20    375
21    354
22    403
23    433
24    418
25    345
26    364
27    406
28    412
29    426
30    414
31    377
32    346
33    344
34    429
35    356
36    375
37    312
38    415
39    345
40    330
41    427
42    370
43    360
44    363
45    393
46    362
47    381
48    364
49    372
50    456
dtype: int64

In [6]:
def cal2(s):
    nums = int(s[s<60].count())
    return nums
scores_df1['不及格的科目'] = scores_df.apply(cal2,axis=1)
scores_df1

科目  國文  英文   數學   地理   歷史  不及格的科目
學號
1   55  61   78   83   60       1
2   67  87   95   87   60       0
3   96  60   71   89   56       1
4   69  54   86   76   84       1
5   78  74  100   85   90       0
6   67  90   96   64  100       0
7   97  65   55   82   91       1
8   92  93   85   92   61       0
9   82  62   95   58   83       1
10  54  96   93   90   56       2
11  60  71   94   85   97       0
12  85  92   57   75   65       1
13  61  89   65   77   50       1
14  57  59   72   80   99       2
15  83  75   53   95   96       1
16  84  75   93   86   99       0
17  50  85   79   94   58       2
18  82  72   61   64   90       0
19  81  89   53   56   57       3
20  76  84   99   57   59       2
21  52  65   92   59   86       2
22  92  63   60   94   94       0
23  92  78   94   73   96       0
24  67  87   87   80   97       0
25  66  52   79   50   98       2
26  63  76   99   50   76       1
27  77  72   76   95   86       0
28  77  96   52   90   97       1
29  88  66   91   90   91       0
30  85  71  100   99   59       1
31  89  82   77   78   51       1
32  65  73   58   67   83       1
33  54  76   60   93   61       1
34  99  53   92   88   97       1
35  93  55   69   76   63       1
36  75  95   54   82   69       1
37  62  61   61   69   59       1
38  74  71   95   95   80       0
39  64  67   64   84   66       0
40  70  97   51   50   62       2
41  98  84   76   87   82       0
42  84  73   81   66   66       0
43  70  79   61   61   89       0
44  51  84   53   83   92       2
45  97  50   87   74   85       1
46  58  86   55   74   89       2
47  93  76   58   94   60       1
48  92  65   85   57   65       1
49  82  54   80   95   61       1
50  83  86   98  100   89       0

In [7]:
def cal3(s):
    return pd.Series([s.min(),s.max(),s.std()],index=['最低分','最高分','標準差'])
scores_df3 = scores_df.apply(cal3)

In [8]:
display(scores_df)
scores_df3

科目  國文  英文   數學   地理   歷史
學號
1   55  61   78   83   60
2   67  87   95   87   60
3   96  60   71   89   56
4   69  54   86   76   84
5   78  74  100   85   90
6   67  90   96   64  100
7   97  65   55   82   91
8   92  93   85   92   61
9   82  62   95   58   83
10  54  96   93   90   56
11  60  71   94   85   97
12  85  92   57   75   65
13  61  89   65   77   50
14  57  59   72   80   99
15  83  75   53   95   96
16  84  75   93   86   99
17  50  85   79   94   58
18  82  72   61   64   90
19  81  89   53   56   57
20  76  84   99   57   59
21  52  65   92   59   86
22  92  63   60   94   94
23  92  78   94   73   96
24  67  87   87   80   97
25  66  52   79   50   98
26  63  76   99   50   76
27  77  72   76   95   86
28  77  96   52   90   97
29  88  66   91   90   91
30  85  71  100   99   59
31  89  82   77   78   51
32  65  73   58   67   83
33  54  76   60   93   61
34  99  53   92   88   97
35  93  55   69   76   63
36  75  95   54   82   69
37  62  61   61   69   59
38  74  71   95   95   80
39  64  67   64   84   66
40  70  97   51   50   62
41  98  84   76   87   82
42  84  73   81   66   66
43  70  79   61   61   89
44  51  84   53   83   92
45  97  50   87   74   85
46  58  86   55   74   89
47  93  76   58   94   60
48  92  65   85   57   65
49  82  54   80   95   61
50  83  86   98  100   89

科目         國文         英文          數學          地理          歷史
最低分  50.00000  50.000000   51.000000   50.000000   50.000000
最高分  99.00000  97.000000  100.000000  100.000000  100.000000
標準差  14.48794  13.217552   16.537218   14.241589   16.279447

In [10]:
pd.concat([scores_df,scores_df3]).style\
.format({
    '國文':"{:.2f}",
    '英文':"{:.2f}",
    '數學':"{:.2f}",
    '地理':"{:.2f}",
    '歷史':"{:.2f}"
})